version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ibms
      POSTGRES_PASSWORD: ibms_password
      POSTGRES_DB: ibms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - mailhog
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: