import { db } from '@/db';
import { agents } from '@/db/schema';

async function main() {
    const sampleAgents = [
        {
            type: 'individual',
            fullName: 'Adebayo Johnson',
            email: 'adebayo.johnson@gmail.com',
            phone: '+2348012345678',
            defaultCommissionPct: 3.5,
            commissionModel: 'flat',
            status: 'active',
            legalName: null,
            cacRc: null,
            tin: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            type: 'individual',
            fullName: 'Fatima Abdullahi',
            email: 'fatima.abdullahi@yahoo.com',
            phone: '+2347087654321',
            defaultCommissionPct: 5.0,
            commissionModel: 'variable',
            status: 'active',
            legalName: null,
            cacRc: null,
            tin: null,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            type: 'corporate',
            legalName: 'Prime Insurance Brokers Limited',
            cacRc: 'RC234567',
            tin: '23456789-0001',
            email: 'info@primebrokers.com.ng',
            phone: '+2349091234567',
            defaultCommissionPct: 7.5,
            commissionModel: 'flat',
            status: 'active',
            fullName: null,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            type: 'individual',
            fullName: 'Chinedu Okafor',
            email: 'chinedu.okafor@hotmail.com',
            phone: '+2347034567890',
            defaultCommissionPct: 2.5,
            commissionModel: 'flat',
            status: 'active',
            legalName: null,
            cacRc: null,
            tin: null,
            createdAt: new Date('2024-04-20').toISOString(),
            updatedAt: new Date('2024-04-20').toISOString(),
        },
        {
            type: 'individual',
            fullName: 'Amina Hassan',
            email: 'amina.hassan@company.ng',
            phone: '+2348023456789',
            defaultCommissionPct: 6.0,
            commissionModel: 'variable',
            status: 'inactive',
            legalName: null,
            cacRc: null,
            tin: null,
            createdAt: new Date('2024-05-12').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        },
        {
            type: 'corporate',
            legalName: 'Lagos Financial Consultants Plc',
            cacRc: 'RC345678',
            tin: '34567890-0002',
            email: 'contact@lagosfinancial.ng',
            phone: '+2347012345678',
            defaultCommissionPct: 5.5,
            commissionModel: 'variable',
            status: 'active',
            fullName: null,
            createdAt: new Date('2024-06-08').toISOString(),
            updatedAt: new Date('2024-06-08').toISOString(),
        },
        {
            type: 'individual',
            fullName: 'Musah Tanko',
            email: 'musah.tanko@outlook.com',
            phone: '+2348056789012',
            defaultCommissionPct: 4.0,
            commissionModel: 'flat',
            status: 'active',
            legalName: null,
            cacRc: null,
            tin: null,
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-07-25').toISOString(),
        },
        {
            type: 'corporate',
            legalName: 'Abuja Risk Management & Associates',
            cacRc: 'RC456789',
            tin: '45678901-0003',
            email: 'admin@abujarisk.ng',
            phone: '+2347089012345',
            defaultCommissionPct: 8.5,
            commissionModel: 'flat',
            status: 'active',
            fullName: null,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            type: 'individual',
            fullName: 'Ngozi Eze',
            email: 'ngozi.eze@gmail.com',
            phone: '+2348067890123',
            defaultCommissionPct: 7.5,
            commissionModel: 'variable',
            status: 'active',
            legalName: null,
            cacRc: null,
            tin: null,
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-10').toISOString(),
        },
        {
            type: 'corporate',
            legalName: 'Eko Insurance Services Limited',
            cacRc: 'RC567890',
            tin: '56789012-0004',
            email: 'info@ekoinsurance.com.ng',
            phone: '+2348078901234',
            defaultCommissionPct: 10.0,
            commissionModel: 'variable',
            status: 'active',
            fullName: null,
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
    ];

    await db.insert(agents).values(sampleAgents);
    
    console.log('✅ Agents seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});