import { db } from '@/db';
import { bankAccounts } from '@/db/schema';

async function main() {
    const sampleBankAccounts = [
        {
            ownerType: 'Client',
            ownerId: 1,
            bankName: 'First Bank of Nigeria',
            branch: 'Marina Branch, Lagos',
            accountNumber: '2012345678',
            accountCountry: 'NG',
            currency: 'NGN',
            swiftBic: 'FBNINGLA',
            usageReceivable: true,
            usagePayable: false,
            isDefault: true,
            statementSource: 'CSV',
            glCode: '120001',
            active: true,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            ownerType: 'Client',
            ownerId: 1,
            bankName: 'Guaranty Trust Bank',
            branch: 'Victoria Island, Lagos',
            accountNumber: '0023456789',
            accountCountry: 'NG',
            currency: 'NGN',
            swiftBic: 'GTBINGLA',
            usageReceivable: false,
            usagePayable: true,
            isDefault: true,
            statementSource: 'API',
            glCode: '210001',
            active: true,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            ownerType: 'Insurer',
            ownerId: 1,
            bankName: 'Zenith Bank',
            branch: 'Akure Main Branch',
            accountNumber: '1012345678',
            accountCountry: 'NG',
            currency: 'NGN',
            swiftBic: 'ZEIBNGLA',
            usageReceivable: true,
            usagePayable: false,
            isDefault: false,
            statementSource: 'Manual',
            glCode: '130001',
            active: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            ownerType: 'Insurer',
            ownerId: 1,
            bankName: 'Access Bank',
            branch: 'Alausa, Ikeja',
            accountNumber: '0765432109',
            accountCountry: 'NG',
            currency: 'NGN',
            swiftBic: 'ABNGNGLA',
            usageReceivable: false,
            usagePayable: true,
            isDefault: true,
            statementSource: 'CSV',
            glCode: '220001',
            active: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            ownerType: 'Agent',
            ownerId: 1,
            bankName: 'United Bank for Africa',
            branch: 'Broad Street, Lagos',
            accountNumber: '0332145698',
            accountCountry: 'NG',
            currency: 'NGN',
            swiftBic: 'UNAFNGLA',
            usageReceivable: true,
            usagePayable: false,
            isDefault: true,
            statementSource: 'API',
            glCode: '140001',
            active: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            ownerType: 'Agent',
            ownerId: 1,
            bankName: 'HSBC Bank',
            branch: 'New York, USA',
            accountNumber: '123456789012',
            accountCountry: 'US',
            currency: 'USD',
            swiftBic: 'HSBCUS33',
            usageReceivable: false,
            usagePayable: true,
            isDefault: true,
            statementSource: 'Manual',
            glCode: '230001',
            active: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
    ];

    await db.insert(bankAccounts).values(sampleBankAccounts);
    
    console.log('✅ Bank accounts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});