import { db } from '@/db';
import { lobs } from '@/db/schema';

async function main() {
    const sampleLobs = [
        {
            name: 'Motor Insurance',
            code: 'MOT',
            description: 'Comprehensive motor vehicle insurance covering private and commercial vehicles',
            status: 'active',
            defaultBrokeragePct: 12.5,
            defaultVatPct: 7.5,
            rateBasis: 'Sum Insured',
            minPremium: 25000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Fire & Special Perils',
            code: 'FIRE',
            description: 'Fire insurance and allied perils covering buildings, contents, and business interruption',
            status: 'active',
            defaultBrokeragePct: 15.0,
            defaultVatPct: 7.5,
            rateBasis: 'Sum Insured',
            minPremium: 50000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'General Accident',
            code: 'GAC',
            description: 'Personal accident and group life insurance covering individuals and employees',
            status: 'active',
            defaultBrokeragePct: 10.0,
            defaultVatPct: 7.5,
            rateBasis: 'Sum Insured',
            minPremium: 20000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Marine Insurance',
            code: 'MAR',
            description: 'Marine cargo and hull insurance covering goods in transit and vessels',
            status: 'active',
            defaultBrokeragePct: 12.0,
            defaultVatPct: 7.5,
            rateBasis: 'Sum Insured',
            minPremium: 30000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Engineering',
            code: 'ENG',
            description: 'Engineering insurance covering contractors all risks, machinery breakdown, and plant insurance',
            status: 'active',
            defaultBrokeragePct: 10.0,
            defaultVatPct: 7.5,
            rateBasis: 'Sum Insured',
            minPremium: 100000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Bonds & Guarantees',
            code: 'BNG',
            description: 'Surety bonds and bank guarantees for performance and financial obligations',
            status: 'active',
            defaultBrokeragePct: 8.0,
            defaultVatPct: 7.5,
            rateBasis: 'Sum Insured',
            minPremium: 50000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Life Assurance',
            code: 'LIFE',
            description: 'Life insurance covering death, terminal illness, and life savings products',
            status: 'active',
            defaultBrokeragePct: 5.0,
            defaultVatPct: 7.5,
            rateBasis: 'Premium',
            minPremium: 15000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Health Insurance',
            code: 'HMO',
            description: 'Health maintenance organization insurance covering medical expenses and hospitalization',
            status: 'active',
            defaultBrokeragePct: 10.0,
            defaultVatPct: 7.5,
            rateBasis: 'Premium',
            minPremium: 20000,
            ratingInputs: null,
            wordingRefs: null,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
    ];

    await db.insert(lobs).values(sampleLobs);
    
    console.log('✅ LOBs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});